from Players.humanPlayer    import HumanPlayer
from Players.randomPlayer   import RandomPlayer
from Players.harePlayer     import HarePlayer
from Players.snailPlayer    import SnailPlayer
from Players.greedyPlayer   import GreedyPlayer
from Players.selflessPlayer import SelflessPlayer
from Players.runnerPlayer   import RunnerPlayer
from Players.chaserPlayer   import ChaserPlayer
from Players.connectPlayer  import ConnectedPlayer